select * from customer limit 20

--Q1. What is the total revenue generated by male vs female customer?

SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender

--Q2. Which customers used a discount but still spent more than the average purchase amount

SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' and purchase_amount >= (SELECT AVG(purchase_amount) from customer)

--Q3. Which are the top 5 products with the highest average review rating?

SELECT item_purchased, ROUND(AVG(review_rating::numeric),2) AS "Average Product Rating"
from customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) desc
LIMIT 5;

--Q4. Compare average purchase amount btw Standard and Express Shipping

select shipping_type, ROUND(AVG(purchase_amount),2)
from customer
where shipping_type IN ('Standard', 'Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare avg spend and total revenue between subs and non subs

select subscription_status,
COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount),2) AS avg_spend,
ROUND(SUM(purchase_amount),2) AS total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc


--Q6. Which 5 products have the highest % of purchases with discounts applied?

select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7. Segment customers into New, Returning and Loyal based on their total number of previous purchases & show the count of each segment

with customer_type AS(
select customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer
	
)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment

--Q8. What are the top 3 most purchased products within each category

with item_counts as (
select category, item_purchased, count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id)DESC) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank<=3


--Q9. Are customers who are repeat buyers(more than 5 prev purch) also likely to subcribe?

select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status


--Q10. What is the revenue contribution of each age group?

select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc